import {
  IsEmail,
  IsNotEmpty,
  IsNumberString,
  MinLength,
} from 'class-validator';

export class UserDto {
  id: number; //autogenerated

  user_id: string; // uuid

  @IsNotEmpty()
  @MinLength(3)
  first_name: string;

  @IsNotEmpty()
  @MinLength(3)
  last_name: string;

  @IsNumberString()
  @IsNotEmpty()
  phone: string;

  @IsNotEmpty()
  @IsEmail()
  email: string;

  @IsNotEmpty()
  @MinLength(1)
  sex: string;

  @IsNotEmpty()
  @IsNumberString()
  country_id: number;

  created_at: Date;

  update_at: Date;

  @IsNotEmpty()
  status: boolean;
}

export class UserRO {
  first_name: string;
  last_name: string;
  phone: string;
  email: string;
  sex: string;
  country_id: number;
  status: boolean;
}

export class LoginDto {
  email: string;
}
