import { ApiProperty } from '@nestjs/swagger';
import {
  IsEmail,
  IsNotEmpty,
  IsNumberString,
  MinLength,
  MaxLength,
} from 'class-validator';

export class UserDto {
  id: number; //autogenerated

  user_id: string; // uuid
  @ApiProperty({
    title: 'firstName',
    type: String,
  })
  @IsNotEmpty()
  @MinLength(3)
  first_name: string;

  @ApiProperty({
    title: 'lastName',
    type: String,
  })
  @IsNotEmpty()
  @MinLength(3)
  last_name: string;

  @IsNumberString()
  @IsNotEmpty()
  @ApiProperty({
    title: 'PhoneNumber',
    type: String,
  })
  phone: string;

  @IsNotEmpty()
  @IsEmail()
  @ApiProperty({
    title: 'email',
    type: String,
  })
  email: string;

  @IsNotEmpty()
  @MinLength()
  @ApiProperty({
    title: 'Gender',
    type: String,
  })
  sex: string;

  @IsNotEmpty()
  @IsNumberString()
  @ApiProperty({
    title: 'CountryId',
    type: Number,
  })
  country_id: number;

  created_at: Date;

  update_at: Date;

  status: boolean;
}
export class UpdateDto {
  @ApiProperty({
    title: 'firstName',
    type: String,
  })
  // @IsNotEmpty()
  @MinLength(3)
  first_name: string;

  @ApiProperty({
    title: 'lastName',
    type: String,
  })
  // @IsNotEmpty()
  @MinLength(3)
  last_name: string;

  @ApiProperty({
    title: 'PhoneNumber',
    type: String,
  })
  @IsNumberString()
  // @IsNotEmpty()
  phone: string;

  @ApiProperty({
    title: 'email',
    type: String,
  })
  // @IsNotEmpty()
  @IsEmail()
  email: string;

  @ApiProperty({
    title: 'gender',
    type: String,
  })
  // @IsNotEmpty()
  @MaxLength(6)
  sex: string;

  created_at: Date;

  update_at: Date;
}

export class UserRO {
  @ApiProperty({
    title: 'firstName',
    type: String,
  })
  first_name: string;

  @ApiProperty({
    title: 'lastName',
    type: String,
  })
  last_name: string;

  @ApiProperty({
    title: 'PhoneNumber',
    type: String,
  })
  phone: string;

  @ApiProperty({
    title: 'email',
    type: String,
  })
  email: string;

  @ApiProperty({
    title: 'gender',
    type: String,
  })
  sex: string;
  status: boolean;
}

export class LoginDto {
  @ApiProperty({
    title: 'email',
    type: String,
  })
  email: string;
}
